// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_crPEng5X_iT4JwMHLgPbBvOkeadOAvo',
    appId: '1:808671425071:web:af6f0962a1ec74febcccda',
    messagingSenderId: '808671425071',
    projectId: 'fitmate-ced11',
    authDomain: 'fitmate-ced11.firebaseapp.com',
    storageBucket: 'fitmate-ced11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnGBJQdbcYespwoCG60M-CR747-N3otQ',
    appId: '1:808671425071:android:d2a5816f5fba8bf5bcccda',
    messagingSenderId: '808671425071',
    projectId: 'fitmate-ced11',
    storageBucket: 'fitmate-ced11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMfZzQLP29iLGzhy_JvDQxXVmvx4QEKV0',
    appId: '1:808671425071:ios:78a5779aad340e49bcccda',
    messagingSenderId: '808671425071',
    projectId: 'fitmate-ced11',
    storageBucket: 'fitmate-ced11.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMfZzQLP29iLGzhy_JvDQxXVmvx4QEKV0',
    appId: '1:808671425071:ios:78a5779aad340e49bcccda',
    messagingSenderId: '808671425071',
    projectId: 'fitmate-ced11',
    storageBucket: 'fitmate-ced11.firebasestorage.app',
    iosBundleId: 'com.example.fitmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_crPEng5X_iT4JwMHLgPbBvOkeadOAvo',
    appId: '1:808671425071:web:8fc4fc3e4e1f123dbcccda',
    messagingSenderId: '808671425071',
    projectId: 'fitmate-ced11',
    authDomain: 'fitmate-ced11.firebaseapp.com',
    storageBucket: 'fitmate-ced11.firebasestorage.app',
  );
}
